version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt
          cd sw-project && make html
      - store_test_results:
          path: sw-project/_build/html
